---
- name: Create temp dir
  shell: "mkdir /home/ansible/TMP/"
  ignore_errors: True

- name: Copy rc.sql
  copy:
    src: rc.sql
    dest: "/home/ansible/TMP/rc.sql"
    owner: ansible

- name: Execute rc.sql
  community.postgresql.postgresql_query:
    db: cs
    path_to_script: /home/ansible/TMP/rc.sql
    login_user: cs
    login_password: 38csQa*
    as_single_query: yes
