---
- name: "Back up the database"
  postgresql_db:
    state: dump
    name: "cs"
    login_user: cs
    login_password: "q3b7v)GS2"
    target: "/home/ansible/backups/{{ lookup('pipe', 'date +%Y_%m_%d') }}.dump.gz"
