apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"frontend-loadbalancer","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"frontend"},"type":"LoadBalancer"}}
    loadbalancer.openstack.org/load-balancer-id: def0f574-bcee-484b-b183-21ac484cb534
  creationTimestamp: "2023-08-22T17:00:09Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: frontend-loadbalancer
  namespace: default
  resourceVersion: "11799644"
  uid: 55e168f0-4958-4085-83e7-914617aff0dc
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.254.180.187
  clusterIPs:
  - 10.254.180.187
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30503
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 87.239.110.24
