apiVersion: v1
kind: Service
metadata:
  name: riverdoc-front-loadbalancer
  namespace: riverdoc
spec:
  selector:
    app: riverdoc-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # приложение слушает на порту 30489
  type: LoadBalancer
