apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: riverdoc
data:
  default.conf: |
    location /rest/ {
      proxy_pass http://frontend-loadbalancer:8787;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;
    }
