apiVersion: v1
kind: Service
metadata:
  name: riverdoc-loadbalancer
  namespace: riverdoc
spec:
  selector:
    app: riverdoc-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: riverdoc-loadbalancer-back
  namespace: riverdoc
spec:
  selector:
    app: riverdoc-back
  ports:
    - protocol: TCP
      port: 8787
      targetPort: 8787
  type: LoadBalancer
