apiVersion: v1
kind: Service
metadata:
  name: riverdoc-front-nodeport
  namespace: riverdoc
spec:
  selector:
    app: riverdoc-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000  # здесь я могу задать нужный порт
  type: NodePort
